version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      node:
        patterns:
          - "*"
