version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      node:
        patterns:
          - "*"
    ignore:
      - dependency-name: '@bufbuild/protobuf'
        versions:
          - ">= 2"
