// @generated by protoc-gen-es v1.9.0
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, type proto3 } from "@bufbuild/protobuf";

/**
 * The settings for a user.
 *
 * @generated from message frontendapi.User
 */
export declare class User extends Message<User> {
  /**
   * IDs of programming languages that reviews can be created for.
   * IDs correspond to `language_id` from github-linguist.
   * https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml
   * Required.
   *
   * @generated from field: repeated uint32 programming_language_ids = 1;
   */
  programmingLanguageIds: number[];

  /**
   * The maximum number of reviews created by the app that can be open at once.
   * Required.
   *
   * @generated from field: optional uint32 max_open_reviews = 2;
   */
  maxOpenReviews?: number;

  constructor(data?: PartialMessage<User>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "frontendapi.User";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): User;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): User;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): User;

  static equals(
    a: User | PlainMessage<User> | undefined,
    b: User | PlainMessage<User> | undefined,
  ): boolean;
}

/**
 * A request for FrontendService.CreateUser.
 *
 * @generated from message frontendapi.CreateUserRequest
 */
export declare class CreateUserRequest extends Message<CreateUserRequest> {
  /**
   * The user to create.
   * Required.
   *
   * @generated from field: optional frontendapi.User user = 1;
   */
  user?: User;

  constructor(data?: PartialMessage<CreateUserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "frontendapi.CreateUserRequest";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): CreateUserRequest;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): CreateUserRequest;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): CreateUserRequest;

  static equals(
    a: CreateUserRequest | PlainMessage<CreateUserRequest> | undefined,
    b: CreateUserRequest | PlainMessage<CreateUserRequest> | undefined,
  ): boolean;
}

/**
 * A response for FrontendService.CreateUser.
 *
 * Empty to allow future extension.
 *
 * @generated from message frontendapi.CreateUserResponse
 */
export declare class CreateUserResponse extends Message<CreateUserResponse> {
  constructor(data?: PartialMessage<CreateUserResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "frontendapi.CreateUserResponse";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): CreateUserResponse;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): CreateUserResponse;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): CreateUserResponse;

  static equals(
    a: CreateUserResponse | PlainMessage<CreateUserResponse> | undefined,
    b: CreateUserResponse | PlainMessage<CreateUserResponse> | undefined,
  ): boolean;
}
