// @generated by protoc-gen-es v1.9.0
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * The settings for a user.
 *
 * @generated from message frontendapi.User
 */
export const User = /*@__PURE__*/ proto3.makeMessageType(
  "frontendapi.User",
  () => [
    {
      no: 1,
      name: "programming_language_ids",
      kind: "scalar",
      T: 13 /* ScalarType.UINT32 */,
      repeated: true,
    },
    {
      no: 2,
      name: "max_open_reviews",
      kind: "scalar",
      T: 13 /* ScalarType.UINT32 */,
    },
  ],
);

/**
 * A request for FrontendService.GetUser.
 *
 * @generated from message frontendapi.GetUserRequest
 */
export const GetUserRequest = /*@__PURE__*/ proto3.makeMessageType(
  "frontendapi.GetUserRequest",
  [],
);

/**
 * A response for FrontendService.GetUser.
 *
 * @generated from message frontendapi.GetUserResponse
 */
export const GetUserResponse = /*@__PURE__*/ proto3.makeMessageType(
  "frontendapi.GetUserResponse",
  () => [{ no: 1, name: "user", kind: "message", T: User }],
);

/**
 * A request for FrontendService.SaveUser.
 *
 * @generated from message frontendapi.SaveUserRequest
 */
export const SaveUserRequest = /*@__PURE__*/ proto3.makeMessageType(
  "frontendapi.SaveUserRequest",
  () => [{ no: 1, name: "user", kind: "message", T: User }],
);

/**
 * A response for FrontendService.SaveUser.
 *
 * Empty to allow future extension.
 *
 * @generated from message frontendapi.SaveUserResponse
 */
export const SaveUserResponse = /*@__PURE__*/ proto3.makeMessageType(
  "frontendapi.SaveUserResponse",
  [],
);
