// @generated by protoc-gen-connect-es v1.4.0
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, CreateUserResponse } from "./frontend_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The service for the frontend.
 *
 * @generated from service frontendapi.FrontendService
 */
export const FrontendService = {
  typeName: "frontendapi.FrontendService",
  methods: {
    /**
     * Creates a new user.
     *
     * @generated from rpc frontendapi.FrontendService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
  },
};
