// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file frontendapi/frontend.proto.
 */
export const file_frontendapi_frontend: GenFile = /*@__PURE__*/
  fileDesc("Chpmcm9udGVuZGFwaS9mcm9udGVuZC5wcm90bxILZnJvbnRlbmRhcGkiQgoEVXNlchIgChhwcm9ncmFtbWluZ19sYW5ndWFnZV9pZHMYASADKA0SGAoQbWF4X29wZW5fcmV2aWV3cxgCIAEoDSIQCg5HZXRVc2VyUmVxdWVzdCIyCg9HZXRVc2VyUmVzcG9uc2USHwoEdXNlchgBIAEoCzIRLmZyb250ZW5kYXBpLlVzZXIiMgoPU2F2ZVVzZXJSZXF1ZXN0Eh8KBHVzZXIYASABKAsyES5mcm9udGVuZGFwaS5Vc2VyIhIKEFNhdmVVc2VyUmVzcG9uc2UyoAEKD0Zyb250ZW5kU2VydmljZRJECgdHZXRVc2VyEhsuZnJvbnRlbmRhcGkuR2V0VXNlclJlcXVlc3QaHC5mcm9udGVuZGFwaS5HZXRVc2VyUmVzcG9uc2USRwoIU2F2ZVVzZXISHC5mcm9udGVuZGFwaS5TYXZlVXNlclJlcXVlc3QaHS5mcm9udGVuZGFwaS5TYXZlVXNlclJlc3BvbnNlQjtaOWdpdGh1Yi5jb20vY3VyaW9zd2l0Y2gvdGFzdWtlL2Zyb250ZW5kL2FwaS9nbztmcm9udGVuZGFwaWIGcHJvdG8z");

/**
 * The settings for a user.
 *
 * @generated from message frontendapi.User
 */
export type User = Message<"frontendapi.User"> & {
  /**
   * IDs of programming languages that reviews can be created for.
   * IDs correspond to `language_id` from github-linguist.
   * https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml
   * Required.
   *
   * @generated from field: repeated uint32 programming_language_ids = 1;
   */
  programmingLanguageIds: number[];

  /**
   * The maximum number of reviews created by the app that can be open at once.
   * Required.
   *
   * @generated from field: uint32 max_open_reviews = 2;
   */
  maxOpenReviews: number;
};

/**
 * Describes the message frontendapi.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 0);

/**
 * A request for FrontendService.GetUser.
 *
 * @generated from message frontendapi.GetUserRequest
 */
export type GetUserRequest = Message<"frontendapi.GetUserRequest"> & {
};

/**
 * Describes the message frontendapi.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 1);

/**
 * A response for FrontendService.GetUser.
 *
 * @generated from message frontendapi.GetUserResponse
 */
export type GetUserResponse = Message<"frontendapi.GetUserResponse"> & {
  /**
   * The user information.
   * Required.
   *
   * @generated from field: frontendapi.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message frontendapi.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 2);

/**
 * A request for FrontendService.SaveUser.
 *
 * @generated from message frontendapi.SaveUserRequest
 */
export type SaveUserRequest = Message<"frontendapi.SaveUserRequest"> & {
  /**
   * The user to create.
   * Required.
   *
   * @generated from field: frontendapi.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message frontendapi.SaveUserRequest.
 * Use `create(SaveUserRequestSchema)` to create a new message.
 */
export const SaveUserRequestSchema: GenMessage<SaveUserRequest> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 3);

/**
 * A response for FrontendService.SaveUser.
 *
 * Empty to allow future extension.
 *
 * @generated from message frontendapi.SaveUserResponse
 */
export type SaveUserResponse = Message<"frontendapi.SaveUserResponse"> & {
};

/**
 * Describes the message frontendapi.SaveUserResponse.
 * Use `create(SaveUserResponseSchema)` to create a new message.
 */
export const SaveUserResponseSchema: GenMessage<SaveUserResponse> = /*@__PURE__*/
  messageDesc(file_frontendapi_frontend, 4);

/**
 * The service for the frontend.
 *
 * @generated from service frontendapi.FrontendService
 */
export const FrontendService: GenService<{
  /**
   * Gets information for the current user.
   *
   * @generated from rpc frontendapi.FrontendService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * Saves information for a user. This method works both for a new or existing user.
   * The user is identified by the firebase ID token included in the authorization header.
   *
   * @generated from rpc frontendapi.FrontendService.SaveUser
   */
  saveUser: {
    methodKind: "unary";
    input: typeof SaveUserRequestSchema;
    output: typeof SaveUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_frontendapi_frontend, 0);

