// @generated by protoc-gen-connect-es v1.4.0
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  GetUserRequest,
  GetUserResponse,
  SaveUserRequest,
  SaveUserResponse,
} from "./frontend_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The service for the frontend.
 *
 * @generated from service frontendapi.FrontendService
 */
export const FrontendService = {
  typeName: "frontendapi.FrontendService",
  methods: {
    /**
     * Gets information for the current user.
     *
     * @generated from rpc frontendapi.FrontendService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Saves information for a user. This method works both for a new or existing user.
     * The user is identified by the firebase ID token included in the authorization header.
     *
     * @generated from rpc frontendapi.FrontendService.SaveUser
     */
    saveUser: {
      name: "SaveUser",
      I: SaveUserRequest,
      O: SaveUserResponse,
      kind: MethodKind.Unary,
    },
  },
};
