// @generated by protoc-gen-connect-query v1.4.0 with parameter "target=ts"
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import {
  GetUserRequest,
  GetUserResponse,
  SaveUserRequest,
  SaveUserResponse,
} from "./frontend_pb.js";

/**
 * Gets information for the current user.
 *
 * @generated from rpc frontendapi.FrontendService.GetUser
 */
export const getUser = {
  localName: "getUser",
  name: "GetUser",
  kind: MethodKind.Unary,
  I: GetUserRequest,
  O: GetUserResponse,
  service: {
    typeName: "frontendapi.FrontendService",
  },
} as const;

/**
 * Saves information for a user. This method works both for a new or existing user.
 * The user is identified by the firebase ID token included in the authorization header.
 *
 * @generated from rpc frontendapi.FrontendService.SaveUser
 */
export const saveUser = {
  localName: "saveUser",
  name: "SaveUser",
  kind: MethodKind.Unary,
  I: SaveUserRequest,
  O: SaveUserResponse,
  service: {
    typeName: "frontendapi.FrontendService",
  },
} as const;
