// @generated by protoc-gen-connect-es v1.4.0
// @generated from file frontendapi/frontend.proto (package frontendapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { MethodKind } from "@bufbuild/protobuf";
import type { CreateUserRequest, CreateUserResponse } from "./frontend_pb.js";

/**
 * The service for the frontend.
 *
 * @generated from service frontendapi.FrontendService
 */
export declare const FrontendService: {
  readonly typeName: "frontendapi.FrontendService";
  readonly methods: {
    /**
     * Creates a new user. Tasuke is a GitHub application and users strongly
     * tied to GitHub users. For example, the user ID used in the system is
     * the GitHub user ID itself.
     *
     * @generated from rpc frontendapi.FrontendService.CreateUser
     */
    readonly createUser: {
      readonly name: "CreateUser";
      readonly I: typeof CreateUserRequest;
      readonly O: typeof CreateUserResponse;
      readonly kind: MethodKind.Unary;
    };
  };
};
